create database ep;
use ep;
create table details(c_code int primary key ,c_name varchar(10),continent varchar(10));
insert into details values(1,"ravi","india");
insert into details values(2,"varun","india");
insert into details values(3,"shruthi","USA");
insert into details values(4,"vamsi","germany");
select * from details;
delete from details where c_code=2;
desc details;
select * from details;
update details set c_name = "ramu" where c_code=3;
select * from details;
update details set continent = "country";
create table profile(id int primary key ,name varchar(10),native varchar(10),dept varchar(5));
insert into profile values(19001,"pranav","vijayawada","cse");
insert into profile values(19002,"vindhya","guntur","ece");
insert into profile values(19003,"sindhu","vijayawada","cse");
insert into profile values(19004,"surya","guntur","ece");
insert into profile values(19005,"satya","vijawada","cse");
select * from profile;
delete from profile where id=19002;
select * from profile;
update profile set dept = "cse" where id=19004;
select * from profile;
alter table details drop continent;
select * from details;
select * from profile;